server:
  port: 8888
  
spring:
  datasource:
    username: ${CB_DB_ROLE}
    password: ${CB_DB_PASS}
    url: ${CB_DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        temp:
          use_jdbc_metadata_default: false
